Repository: plone.namedfile


Branch: refs/heads/master
Date: 2019-07-05T12:37:49+02:00
Author: Laurent Lasudry (laulaz) <lasudry@gmail.com>
Commit: https://github.com/plone/plone.namedfile/commit/fa24f6b865c6f8a107af341d782ddb1cf41d6c26

Fix object URL in error message

Files changed:
M plone/namedfile/scaling.py

b'diff --git a/plone/namedfile/scaling.py b/plone/namedfile/scaling.py\nindex 2723ab6..8a41233 100644\n--- a/plone/namedfile/scaling.py\n+++ b/plone/namedfile/scaling.py\n@@ -251,7 +251,7 @@ def __call__(\n                 logger.exception(\n                     \'Could not scale "{0!r}" of {1!r}\'.format(\n                         orig_value,\n-                        self.context.absolute_url,\n+                        self.context.absolute_url(),\n                     ),\n                 )\n                 return\n'

