Repository: plone.restapi


Branch: refs/heads/master
Date: 2021-08-31T21:47:46+02:00
Author: Wesley Barroso Lopes (wesleybl) <wesleybl@gmail.com>
Commit: https://github.com/plone/plone.restapi/commit/b96f3dfcde7fd60880a117ee03555de52cd5ac7d

Fix tests that involving dates in Python 3.8 on machines that don't use (#1195)

TZ = UTC

In Python 3.8, for the TZ environment variable to be recognized, you
need to call time.tzset()

Ref: https://github.com/plone/buildout.coredev/pull/701

Files changed:
M base.cfg

b"diff --git a/base.cfg b/base.cfg\nindex 94b95b995..00612a63e 100644\n--- a/base.cfg\n+++ b/base.cfg\n@@ -63,6 +63,10 @@ recipe = zc.recipe.testrunner\n eggs = ${instance:eggs}\n initialization =\n     os.environ['TZ'] = 'UTC'\n+    # In Python 3.8+, for the TZ environment variable to be used, it's \n+    # necessary to explicitly call time.tzset().\n+    import time\n+    time.tzset()\n     os.environ['ZSERVER_PORT'] = '55001'\n defaults = ['-s', 'plone.restapi', '--auto-color', '--auto-progress']\n \n"

