Repository: Products.CMFPlone


Branch: refs/heads/master
Date: 2019-03-11T09:16:35+01:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/Products.CMFPlone/commit/fedb0a5c44a4bc17d9ee3449f748929afca505c7

Fix errors that abort the verification when debugging a DB with ./bin/instance verifydb -D

Files changed:
A news/2792.bugfix
M Products/CMFPlone/_scripts/verifydb.py

b"diff --git a/Products/CMFPlone/_scripts/verifydb.py b/Products/CMFPlone/_scripts/verifydb.py\nindex 704ee383f..dbd37582f 100644\n--- a/Products/CMFPlone/_scripts/verifydb.py\n+++ b/Products/CMFPlone/_scripts/verifydb.py\n@@ -64,6 +64,7 @@ def verify_record(oid, data, debug=False):\n     input_file = io.BytesIO(data)\n     unpickler = PersistentUnpickler(None, persistent_load, input_file)\n     class_info = 'unknown'\n+    pos = None\n     try:\n         class_info = unpickler.load()\n         pos = input_file.tell()\n@@ -77,11 +78,15 @@ def verify_record(oid, data, debug=False):\n         ))\n         logger.info(repr(pickle))\n         logger.info(traceback.format_exc())\n-        if debug:\n+        if debug and pos is not None:\n             try:\n                 pickletools.dis(pickle[pos:])\n+            except Exception:\n+                logger.info(traceback.format_exc())\n             finally:\n                 pdb.set_trace()\n+        elif debug and pos is None:\n+            pdb.set_trace()\n         return False\n     return True\n \ndiff --git a/news/2792.bugfix b/news/2792.bugfix\nnew file mode 100644\nindex 000000000..e7c6fc4c2\n--- /dev/null\n+++ b/news/2792.bugfix\n@@ -0,0 +1,2 @@\n+Fix errors that abort the verification when debugging a DB with ./bin/instance verifydb -D.\n+[pbauer]\n\\ No newline at end of file\n"

Repository: Products.CMFPlone


Branch: refs/heads/master
Date: 2019-03-11T09:16:35+01:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/Products.CMFPlone/commit/d3c7e67b2c6809709af77dceab75ece3e300933c

ignore exceptions while disassembling the pickle

Files changed:
M Products/CMFPlone/_scripts/verifydb.py

b'diff --git a/Products/CMFPlone/_scripts/verifydb.py b/Products/CMFPlone/_scripts/verifydb.py\nindex dbd37582f..02e817cc1 100644\n--- a/Products/CMFPlone/_scripts/verifydb.py\n+++ b/Products/CMFPlone/_scripts/verifydb.py\n@@ -82,7 +82,9 @@ def verify_record(oid, data, debug=False):\n             try:\n                 pickletools.dis(pickle[pos:])\n             except Exception:\n-                logger.info(traceback.format_exc())\n+                # ignore exceptions while disassembling the pickle since the\n+                # real issue is that it references a unavailable module\n+                pass\n             finally:\n                 pdb.set_trace()\n         elif debug and pos is None:\n'

Repository: Products.CMFPlone


Branch: refs/heads/master
Date: 2019-03-11T09:17:14+01:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/Products.CMFPlone/commit/f9e3bc6880af5cb3f85e79ec26947a539a62aa7b

Merge pull request #2793 from plone/improve_verifydb_with_debug

Fix errors that abort the verification when debugging a DB

Files changed:
A news/2792.bugfix
M Products/CMFPlone/_scripts/verifydb.py

b"diff --git a/Products/CMFPlone/_scripts/verifydb.py b/Products/CMFPlone/_scripts/verifydb.py\nindex 704ee383f..02e817cc1 100644\n--- a/Products/CMFPlone/_scripts/verifydb.py\n+++ b/Products/CMFPlone/_scripts/verifydb.py\n@@ -64,6 +64,7 @@ def verify_record(oid, data, debug=False):\n     input_file = io.BytesIO(data)\n     unpickler = PersistentUnpickler(None, persistent_load, input_file)\n     class_info = 'unknown'\n+    pos = None\n     try:\n         class_info = unpickler.load()\n         pos = input_file.tell()\n@@ -77,11 +78,17 @@ def verify_record(oid, data, debug=False):\n         ))\n         logger.info(repr(pickle))\n         logger.info(traceback.format_exc())\n-        if debug:\n+        if debug and pos is not None:\n             try:\n                 pickletools.dis(pickle[pos:])\n+            except Exception:\n+                # ignore exceptions while disassembling the pickle since the\n+                # real issue is that it references a unavailable module\n+                pass\n             finally:\n                 pdb.set_trace()\n+        elif debug and pos is None:\n+            pdb.set_trace()\n         return False\n     return True\n \ndiff --git a/news/2792.bugfix b/news/2792.bugfix\nnew file mode 100644\nindex 000000000..e7c6fc4c2\n--- /dev/null\n+++ b/news/2792.bugfix\n@@ -0,0 +1,2 @@\n+Fix errors that abort the verification when debugging a DB with ./bin/instance verifydb -D.\n+[pbauer]\n\\ No newline at end of file\n"

