Repository: Products.PlonePAS


Branch: refs/heads/master
Date: 2016-02-12T21:44:20+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.PlonePAS/commit/f241b8c1943de23c3f780de950ce9321e4bbeca9

Fixed AttributeError with Python 2.6 when reading setup.py.

install_requires inadvertently was a list and after this a comma,
which turned it into a tuple with a list as only value.
Strangely, this worked fine in Python 2.7.
But in Python 2.6 we then tried to append to this tuple, which failed.

Files changed:
M CHANGES.rst
M setup.py

diff --git a/CHANGES.rst b/CHANGES.rst
index eb5b7c7..7152180 100644
--- a/CHANGES.rst
+++ b/CHANGES.rst
@@ -10,7 +10,7 @@ New:
 
 Fixes:
 
-- *add item here*
+- Fixed AttributeError with Python 2.6 when reading setup.py.  [maurits]
 
 
 5.0.7 (2016-01-08)
diff --git a/setup.py b/setup.py
index 2df7778..e4f5d37 100644
--- a/setup.py
+++ b/setup.py
@@ -20,7 +20,7 @@
         'setuptools',
         'zope.deprecation',
         'Zope2 >=2.13.22',
-    ],
+    ]
 if sys.version_info < (2, 7):
     # python 2.6 has no collections.ordereddict so we need to use this package
     install_requires.append('ordereddict')


