Repository: plone.app.robotframework


Branch: refs/heads/master
Date: 2019-03-18T13:16:07+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/6c080c9bff7783ea3e6270dee86b858358d06eec

Patch selenium.is_connectable for Python 3 to retry on ConnectionResetError.

Fixes https://github.com/plone/Products.CMFPlone/issues/2786.

Files changed:
A news/2786.bugfix
A src/plone/app/robotframework/patches.py
M src/plone/app/robotframework/__init__.py

b'diff --git a/news/2786.bugfix b/news/2786.bugfix\nnew file mode 100644\nindex 0000000..4f6cf35\n--- /dev/null\n+++ b/news/2786.bugfix\n@@ -0,0 +1,3 @@\n+Patch selenium.is_connectable for Python 3 to retry on ConnectionResetError.\n+See `issue 2786 <https://github.com/plone/Products.CMFPlone/issues/2786>`_.\n+[maurits]\ndiff --git a/src/plone/app/robotframework/__init__.py b/src/plone/app/robotframework/__init__.py\nindex 936c19c..06749a1 100644\n--- a/src/plone/app/robotframework/__init__.py\n+++ b/src/plone/app/robotframework/__init__.py\n@@ -25,3 +25,6 @@\n \n # Robot Plone fixture\n from plone.app.robotframework.testing import PLONE_ROBOT_TESTING\n+\n+# Load our patches.  Call it _patches to mark it as private.\n+from plone.app.robotframework import patches as _patches\ndiff --git a/src/plone/app/robotframework/patches.py b/src/plone/app/robotframework/patches.py\nnew file mode 100644\nindex 0000000..791e2ce\n--- /dev/null\n+++ b/src/plone/app/robotframework/patches.py\n@@ -0,0 +1,25 @@\n+# -*- coding: utf-8 -*-\n+# Patch selenium.is_connectable for Python 3.\n+# See https://github.com/SeleniumHQ/selenium/pull/6480\n+# and for Plone: https://github.com/plone/Products.CMFPlone/issues/2786\n+from selenium.webdriver.common import utils\n+\n+try:\n+    # Python 3\n+    ConnectionResetError\n+except NameError:\n+    # Python 2\n+    ConnectionResetError = None\n+\n+\n+if ConnectionResetError is not None:\n+    orig_is_connectable = utils.is_connectable\n+\n+    def patched_is_connectable(port, host="localhost"):\n+        try:\n+            return orig_is_connectable(port, host=host)\n+        except ConnectionResetError:\n+            # Try again once.\n+            return orig_is_connectable(port, host=host)\n+\n+    utils.is_connectable = patched_is_connectable\n'

Repository: plone.app.robotframework


Branch: refs/heads/master
Date: 2019-03-19T10:41:22+01:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.app.robotframework/commit/3d4a1e6a3130db7f5232aa89d783198441615a99

Merge pull request #108 from plone/maurits-patch-selenium-connectionreseterror

Patch selenium.is_connectable for Python 3 for ConnectionResetError

Files changed:
A news/2786.bugfix
A src/plone/app/robotframework/patches.py
M src/plone/app/robotframework/__init__.py

b'diff --git a/news/2786.bugfix b/news/2786.bugfix\nnew file mode 100644\nindex 0000000..4f6cf35\n--- /dev/null\n+++ b/news/2786.bugfix\n@@ -0,0 +1,3 @@\n+Patch selenium.is_connectable for Python 3 to retry on ConnectionResetError.\n+See `issue 2786 <https://github.com/plone/Products.CMFPlone/issues/2786>`_.\n+[maurits]\ndiff --git a/src/plone/app/robotframework/__init__.py b/src/plone/app/robotframework/__init__.py\nindex 936c19c..06749a1 100644\n--- a/src/plone/app/robotframework/__init__.py\n+++ b/src/plone/app/robotframework/__init__.py\n@@ -25,3 +25,6 @@\n \n # Robot Plone fixture\n from plone.app.robotframework.testing import PLONE_ROBOT_TESTING\n+\n+# Load our patches.  Call it _patches to mark it as private.\n+from plone.app.robotframework import patches as _patches\ndiff --git a/src/plone/app/robotframework/patches.py b/src/plone/app/robotframework/patches.py\nnew file mode 100644\nindex 0000000..791e2ce\n--- /dev/null\n+++ b/src/plone/app/robotframework/patches.py\n@@ -0,0 +1,25 @@\n+# -*- coding: utf-8 -*-\n+# Patch selenium.is_connectable for Python 3.\n+# See https://github.com/SeleniumHQ/selenium/pull/6480\n+# and for Plone: https://github.com/plone/Products.CMFPlone/issues/2786\n+from selenium.webdriver.common import utils\n+\n+try:\n+    # Python 3\n+    ConnectionResetError\n+except NameError:\n+    # Python 2\n+    ConnectionResetError = None\n+\n+\n+if ConnectionResetError is not None:\n+    orig_is_connectable = utils.is_connectable\n+\n+    def patched_is_connectable(port, host="localhost"):\n+        try:\n+            return orig_is_connectable(port, host=host)\n+        except ConnectionResetError:\n+            # Try again once.\n+            return orig_is_connectable(port, host=host)\n+\n+    utils.is_connectable = patched_is_connectable\n'

