Repository: plone.namedfile


Branch: refs/heads/master
Date: 2019-07-05T12:27:50+02:00
Author: Laurent Lasudry (laulaz) <lasudry@gmail.com>
Commit: https://github.com/plone/plone.namedfile/commit/5bd0933160f95801e3728ce41b471768073401fb

Fix object URL in error message

Files changed:
M plone/namedfile/scaling.py

b'diff --git a/plone/namedfile/scaling.py b/plone/namedfile/scaling.py\nindex b12b6f7..2723ab6 100644\n--- a/plone/namedfile/scaling.py\n+++ b/plone/namedfile/scaling.py\n@@ -259,7 +259,7 @@ def __call__(\n             logger.exception(\n                 \'Could not scale "{0!r}" of {1!r}\'.format(\n                     orig_value,\n-                    self.context.absolute_url,\n+                    self.context.absolute_url(),\n                 ),\n             )\n             return\n'

