Repository: plone.restapi


Branch: refs/heads/master
Date: 2018-12-31T13:08:28+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.restapi/commit/e6b601c95ffe3a861679fb5a88418807046605ab

Tests: retry request on ConnectionError.

On Jenkins we often get one ConnectionError in a seemingly random test.
Happens on both Python 2 and 3.
Retrying after a short pause helps.
Fixes https://github.com/plone/plone.restapi/issues/648

Files changed:
M CHANGES.rst
M src/plone/restapi/testing.py

b"diff --git a/CHANGES.rst b/CHANGES.rst\nindex e523a999..611034a5 100644\n--- a/CHANGES.rst\n+++ b/CHANGES.rst\n@@ -6,6 +6,12 @@ Changelog\n \n Bugfixes:\n \n+- Tests: retry request on ConnectionError.\n+  On Jenkins we often get one ConnectionError in a seemingly random test.\n+  Retrying after a short pause helps.\n+  Fixes issue `648 <https://github.com/plone/plone.restapi/issues/648>`_.\n+  [maurits, gforcada]\n+\n - Close the api_session in tests.\n   This prevents lots of ResourceWarnings about unclosed sockets.\n   Fixes issues `636 <https://github.com/plone/plone.restapi/issues/636>`_\ndiff --git a/src/plone/restapi/testing.py b/src/plone/restapi/testing.py\nindex 4786c426..160526cb 100644\n--- a/src/plone/restapi/testing.py\n+++ b/src/plone/restapi/testing.py\n@@ -23,6 +23,7 @@\n from plone.testing.layer import Layer\n from plone.uuid.interfaces import IUUIDGenerator\n from Products.CMFCore.utils import getToolByName\n+from requests.exceptions import ConnectionError\n from six.moves.urllib.parse import urljoin\n from six.moves.urllib.parse import urlparse\n from zope.component import getGlobalSiteManager\n@@ -356,7 +357,14 @@ def request(self, method, url, **kwargs):\n         if urlparse(url).scheme not in ('http', 'https'):\n             url = url.lstrip('/')\n             url = urljoin(self.__base_url, url)\n-        return super(RelativeSession, self).request(method, url, **kwargs)\n+        try:\n+            return super(RelativeSession, self).request(method, url, **kwargs)\n+        except ConnectionError:\n+            # On Jenkins we often get one ConnectionError in a seemingly\n+            # random test, mostly in test_documentation.py.\n+            # The server is still listening: the port is open.  We retry once.\n+            time.sleep(1)\n+            return super(RelativeSession, self).request(method, url, **kwargs)\n \n \n @implementer(IUUIDGenerator)\n"

Repository: plone.restapi


Branch: refs/heads/master
Date: 2018-12-31T19:03:25+01:00
Author: Gil Forcada Codinachs (gforcada) <gil.gnome@gmail.com>
Commit: https://github.com/plone/plone.restapi/commit/e8a9f4f9f218a73c05e05e6abb1a650261c1ebac

Merge pull request #654 from plone/issue-648-retry-on-connectionerror

Tests: retry request on ConnectionError.

Files changed:
M CHANGES.rst
M src/plone/restapi/testing.py

b"diff --git a/CHANGES.rst b/CHANGES.rst\nindex e523a999..611034a5 100644\n--- a/CHANGES.rst\n+++ b/CHANGES.rst\n@@ -6,6 +6,12 @@ Changelog\n \n Bugfixes:\n \n+- Tests: retry request on ConnectionError.\n+  On Jenkins we often get one ConnectionError in a seemingly random test.\n+  Retrying after a short pause helps.\n+  Fixes issue `648 <https://github.com/plone/plone.restapi/issues/648>`_.\n+  [maurits, gforcada]\n+\n - Close the api_session in tests.\n   This prevents lots of ResourceWarnings about unclosed sockets.\n   Fixes issues `636 <https://github.com/plone/plone.restapi/issues/636>`_\ndiff --git a/src/plone/restapi/testing.py b/src/plone/restapi/testing.py\nindex 4786c426..160526cb 100644\n--- a/src/plone/restapi/testing.py\n+++ b/src/plone/restapi/testing.py\n@@ -23,6 +23,7 @@\n from plone.testing.layer import Layer\n from plone.uuid.interfaces import IUUIDGenerator\n from Products.CMFCore.utils import getToolByName\n+from requests.exceptions import ConnectionError\n from six.moves.urllib.parse import urljoin\n from six.moves.urllib.parse import urlparse\n from zope.component import getGlobalSiteManager\n@@ -356,7 +357,14 @@ def request(self, method, url, **kwargs):\n         if urlparse(url).scheme not in ('http', 'https'):\n             url = url.lstrip('/')\n             url = urljoin(self.__base_url, url)\n-        return super(RelativeSession, self).request(method, url, **kwargs)\n+        try:\n+            return super(RelativeSession, self).request(method, url, **kwargs)\n+        except ConnectionError:\n+            # On Jenkins we often get one ConnectionError in a seemingly\n+            # random test, mostly in test_documentation.py.\n+            # The server is still listening: the port is open.  We retry once.\n+            time.sleep(1)\n+            return super(RelativeSession, self).request(method, url, **kwargs)\n \n \n @implementer(IUUIDGenerator)\n"

